apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-connection
  namespace: bobospace
data:
  DATABASE_HOST: postgres.bobospace.svc.cluster.local
  DATABASE_USER: postgres 
  DATABASE_PASSWORD: pass
