apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: bobospace
  labels:
    app: postgres  
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-connection
                  key: DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-connection
                  key: DATABASE_PASSWORD
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "pgdata"
      volumes:
        - hostPath:
            path: "/home/docker/pgdata"
          name: pgdata
